### ISSUE TITLE
Definición Diagrama DER

### ISSUE THREAD

**Issue by abycuestas** [FSAgentesPublicos2022/grupo09-fsap2022-g09#10]

**Comment by abycuestas** [comment]
https://app.diagrams.net/#Wd3eb015f53859cd2%2FD3EB015F53859CD2!1937

**Comment by abycuestas** [comment]
[DER Grupo 9.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9283494/DER.Grupo.9.zip)

**Comment by ggropolo** [comment]
Modificado hasta lo visto ayer... realice uno en otra hoja según mi criterio... analizar est
[grupo9.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9289629/grupo9.zip)
o

**Comment by ggropolo** [comment]
[derzip.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9308133/derzip.zip)

Diagramas trabajados hasta ayer... observe que estado estaba en usuario y cuenta... por eso lo saque a una tabla... observar los diagramas como quedaron
