### ISSUE TITLE
Definicion  de Entidades 

### ISSUE THREAD

**Issue by ggropolo** [FSAgentesPublicos2022/grupo09-fsap2022-g09#11]
Se definieron las entidades presentes en el proyecto de Opcoin

**Comment by ggropolo** [comment]
Se define Der Conceptual del proyect
[derzip.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9416792/derzip.zip)
o

**Comment by abycuestas** [comment]
Se realiza reunión para discutir la definición del DER CONCEPTUAL y se obtiene una nueva versión
[der_opcoin-v2.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9416832/der_opcoin-v2.zip)
