### ISSUE TITLE
Definicion esquema LOGICO

### ISSUE THREAD

**Issue by ggropolo** [FSAgentesPublicos2022/grupo09-fsap2022-g09#12]
Se define esquema logico en base a lo obtenido en  DER Conceptual

**Comment by abycuestas** [comment]
Según las observaciones efectuadas en la exposición en clase del DER Conceptual, se define el esquema LOGICO.
(ver pestaña LOGICO dentro del archivo der_opcoin-v2.drawio)
[der_opcoin-v2.zip](https://github.com/FSAgentesPublicos2022/grupo09-fsap2022-g09/files/9416888/der_opcoin-v2.zip)
